import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/global.css";
import { BiLogoGraphql } from "react-icons/bi";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphql-Next",
  description: "Generated by create next app",
  icons: BiLogoGraphql,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
